services:
  - type: worker
    name: telegram-ingestion-worker
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: node index.js
    rootDir: worker
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ALLOWED_CHAT_IDS
        sync: false
